sudo: required

# Travis by default treated the app like as a ruby app, this line remove it
language: generic

services:
  - docker

before_install:
  - docker build -t matheusr42/docker-react -f Dockerfile.dev .

script:
  - docker run matheusr42/docker-react npm run test -- --coverage